### ISSUE TITLE
Request logger debería ser un middleware y no un request handler

### ISSUE THREAD

**Issue by sluberriaga** [jegutierrez/focus-db#3]
https://github.com/jegutierrez/focus-db/blob/3216364cc4322a7f5cbf679ddfd594a99521854f/app.go#L21

De esta forma podría estar aplicado al grupo, o al router

**Comment by sluberriaga** [comment]
Llamando a c.Next()

**Comment by jegutierrez** [comment]
Done @sluberriaga, gracias!
